// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvoegxsxciinwfybtycb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2b2VneHN4Y2lpbndmeWJ0eWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNDI3MDAsImV4cCI6MjA2MjcxODcwMH0.YAl7Fm4MiX4i6OTjBph3YIknTVWiLpISo_YNhaF0XZ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);